### ISSUE TITLE
SIEM Integration

### ISSUE THREAD

**Issue by tbone8621** [uber-common/metta#11]
Still looking into this, but can this be integrated to a SIEM?

**Comment by carnal0wnage** [comment]
hey @tbone8621 that's super broad. what do you mean specifically?  you want the results of the simulation to go into a SIEM?  you want some kind of hook to check the SIEM for the results of the simulation?

**Comment by paragonsec** [comment]
Wouldn't that be on the OS level? Have your image send it's logs to your SIEM to identify what it detects. I guess a separate log file could be generated and sent off but would probably be easier to configure your VM to send it. That is what I did at least.

**Comment by carnal0wnage** [comment]
gonna wait for @tbone8621 's reply but right now there is some basic json logging that you could do something with. I suspect this more around automatically checking a SIEM for the results of your action or simulation.  It can be done. I ended up creating another celery worker that would query our EDR vendor for the results.  Where using this internally for more rule QA so this is more of a 1-1 match of action to expected alert. This isnt expressly expected with action files or even with scenarios but you could certainly write them with that in mind, where you expect each action run to end up being an event in your SIEM.

**Comment by tbone8621** [comment]
I am looking to see if this could be used to trigger my content in my siem. As in validation testing

**Comment by carnal0wnage** [comment]
assuming the vagrant you build/use has your instrumentation on it and those logs are getting to the SIEM (if necessary...just depends on what you are using for instrumentation) , I don't see why not.  If i'm mis-understanding the question please let me know.

**Comment by tbone8621** [comment]
Thank you that helps, I was just wondering of there was a way to push the data to a siem

**Comment by paragonsec** [comment]
@tbone8621 If it helps I pretty much copied a production system to a VM and installed and configured all the same security tools. Then made sure alerts were sent off normally by manually triggering them.

**Comment by carnal0wnage** [comment]
I think this is closed. @tbone8621  if you still need help please create another issue or i can work with you directly over twitter DM or email.
