### ISSUE TITLE
Feature Request: Kali/Other VM Type

### ISSUE THREAD

**Issue by zombietango** [uber-common/metta#18]
I'd like to add a Kali type to the stable of available vagrant targets. It would be easy to extend the logic for selecting the appropriate Vagrant target/control type for a 4th type, but I prefer to keep the framework as maintained rather than forking it or having to maintain changes. This would be used to perform network-based controls tests using common attack tools already installed in Kali. I'd prefer to keep our Linux system as it is normally built and instrumented rather than putting a bunch of extra stuff on it. 

Thoughts?

**Comment by carnal0wnage** [comment]
yeah i'll take a stab at implementing the above.

**Comment by carnal0wnage** [comment]
@zombietango let me know if https://github.com/uber-common/metta/commit/51e5eeb61975e8671f97a02583ff7bf1511fb7b8 doesnt meet your use case
