### ISSUE TITLE
Add setuid and setgid search for Linux privilege escalation

### ISSUE THREAD

**Issue by paragonsec** [uber-common/metta#7]
Below is the yaml file that could be added to add search functionality for setuid and setgid. This could also be ported to Mac.

-------------------------------------------
enabled: true
meta:
  author: paragonsec
  created: 2018-03-22
  decorations:
  - Purple Team
  description: Find setuid and setgid binaries
  mitre_link: https://attack.mitre.org/wiki/Technique/T1166
  mitre_attack_phase: Privilege Escalation
  mitre_attack_technique: File System setguid and setgid binaries
  purple_actions:
    1: find / -perm -2000 -o -perm -4000 -ls 2>/dev/null
    2: find / -perm -2000 2>/dev/null
    2: find / -perm -4000 2>/dev/null
os: linux
name: Find setuid and setgid binaries
-----------------------------------------------------------------

**Comment by carnal0wnage** [comment]
thanks i should be able to test this today

**Comment by carnal0wnage** [comment]
#https://github.com/uber-common/metta/commit/b1f6f5c037c204a22bb286948aea664344e53015

added. Thank you for the submission.
