### ISSUE TITLE
SSH Key Search Linux CredAccess

### ISSUE THREAD

**Issue by paragonsec** [uber-common/metta#8]
Below is my proposal to add ssh key search on Linux that falls in line with credential access on MITRE ATT&CK. 

-------------------------------------------------------------
enabled: true
meta:
  author: paragonsec
  created: 2018-03-22
  decorations:
  - Purple Team
  description: Search for SSH Keys
  mitre_link: https://attack.mitre.org/wiki/Technique/T1145
  mitre_attack_phase: Credential Access
  mitre_attack_technique: Search for SSH Keys
  purple_actions:
    1: grep /home/ -irw -e "BEGIN RSA PRIVATE" 2>/dev/null > rsa_keys.txt
    2: grep /home/ -irw -e "BEGIN DSA PRIVATE" 2>/dev/null > dsa_keys.txt
os: linux
name: Search for SSH Keys
-------------------------------------------------------------

**Comment by carnal0wnage** [comment]
added via commit https://github.com/uber-common/metta/commit/73e13905d14e91af68e460a3ad126f393c62dc2b

thanks for submitting!
